# Generated by Django 5.1.4 on 2026-02-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_rename_message_feedback_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(choices=[('DAY', 'Day Shift'), ('NIGHT', 'Night Shift'), ('OVERTIME', 'Overtime')], default='DAY', max_length=20),
        ),
    ]
