# Generated by Django 5.1.4 on 2026-02-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_shift_shift_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('DEVELOPMENT', 'Software Development'), ('DESIGN', 'UI/UX Design'), ('QA', 'Quality Assurance'), ('HR', 'Human Resources'), ('MARKETING', 'Digital Marketing'), ('SALES', 'Sales & Business'), ('SUPPORT', 'IT Support & Security')], max_length=50, null=True),
        ),
    ]
