# Generated by Django 5.1.4 on 2026-02-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_customuser_designation_alter_customuser_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='level',
            field=models.CharField(choices=[('JUNIOR', 'Junior Level (Level 1)'), ('INTERMEDIATE', 'Intermediate (Level 2)'), ('SENIOR', 'Senior Level (Level 3)'), ('LEAD', 'Lead Level (Level 4)'), ('EXPERT', 'Expert Level (Level 5)')], default='JUNIOR', max_length=20),
        ),
    ]
