# Generated by Django 5.1.4 on 2026-02-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_customuser_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='task_reports/'),
        ),
    ]
