# Generated by Django 5.1.4 on 2026-02-22 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_task_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='comment',
            new_name='message',
        ),
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('MEETING', 'Meeting'), ('CELEBRATION', 'Celebration'), ('OFFICIAL', 'Official Notice'), ('URGENT', 'Urgent Alert')], default='OFFICIAL', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='hr_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(default='OFFICIAL', max_length=200),
            preserve_default=False,
        ),
    ]
